version: '2.1'
services:
  buildbot:
    build: 
      context: . 
      dockerfile: master/Dockerfile
    env_file:
        - db.env
    environment:
        - BUILDBOT_CONFIG_DIR=config
        - BUILDBOT_WORKER_PORT=9989
        - BUILDBOT_WEB_URL=http://localhost:8010/
        - BUILDBOT_WEB_PORT=tcp:port=8010
    links:
      - db
    depends_on:
      - db
    ports:
      - "8010:8010"
      - "9989:9989"

  db:
    env_file:
        - db.env
    image: "postgres:9.4"
    expose:
        - 5432

  worker:
    build: 
      context: . 
      dockerfile: worker/Dockerfile
    environment:
        BUILDMASTER: buildbot
        BUILDMASTER_PORT: 9989
        WORKERNAME: utility-worker
        WORKERPASS: pass
        WORKER_ENVIRONMENT_BLACKLIST: DOCKER_BUILDBOT* BUILDBOT_ENV_* BUILDBOT_1* WORKER_ENVIRONMENT_BLACKLIST
    links:
        - buildbot
